/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['id', 'content', 'postId', 'userId', 'createdAt', 'updatedAt'] as const
  $columns = CommentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare content: string
  @column()
  declare postId: number | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FollowSchema extends BaseModel {
  static $columns = ['id', 'followerId', 'followingId', 'createdAt'] as const
  $columns = FollowSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare followerId: number | null
  @column()
  declare followingId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class HashtagSchema extends BaseModel {
  static $columns = ['id', 'tag', 'createdAt', 'updatedAt'] as const
  $columns = HashtagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tag: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['id', 'userId', 'postId', 'commentId', 'createdAt', 'updatedAt'] as const
  $columns = LikeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare postId: number | null
  @column()
  declare commentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaSchema extends BaseModel {
  static $columns = ['id', 'postId', 'url', 'type', 'createdAt', 'updatedAt'] as const
  $columns = MediaSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare url: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'actorId', 'type', 'read', 'postId', 'createdAt', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare actorId: number | null
  @column()
  declare type: string
  @column()
  declare read: boolean | null
  @column()
  declare postId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostHashtagSchema extends BaseModel {
  static $columns = ['id', 'postId', 'hashtagId', 'createdAt'] as const
  $columns = PostHashtagSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare hashtagId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = ['id', 'userId', 'title', 'content', 'createdAt', 'updatedAt'] as const
  $columns = PostSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare title: string | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RetweetSchema extends BaseModel {
  static $columns = ['id', 'postId', 'userId', 'createdAt', 'updatedAt'] as const
  $columns = RetweetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserLikeSchema extends BaseModel {
  static $columns = ['id', 'userId', 'postId', 'createdAt', 'updatedAt'] as const
  $columns = UserLikeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare postId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRetweetSchema extends BaseModel {
  static $columns = ['id', 'userId', 'retweetId', 'createdAt'] as const
  $columns = UserRetweetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare retweetId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullname', 'username', 'bio', 'email', 'password', 'location', 'photoProfil', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullname: string | null
  @column()
  declare username: string | null
  @column()
  declare bio: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare location: string | null
  @column()
  declare photoProfil: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
